baseURL = 'https://docs.azpathogens.org/'
languageCode = 'en-us'
title = 'Arizona Pathogens Genomics Analytics Platform Documentation'
theme = 'hugo-book'


[markup.goldmark.renderer]
  unsafe = true

[params]
  BookMenuFoldable = true
  apgapVersion = "FE v1.2.0, BE v1.8.0"
  BookLogo = "images/apgap-logo-horizontal-black.png"
